spring.application.name=restful-web-service
#logging.level.org.springframework=debug

#Path of the segment is used as version
#spring.mvc.apiversion.use.path-segment=0

#Parameter based versioning
#spring.mvc.apiversion.use.query-parameter=version

#Header based versioning
#spring.mvc.apiversion.use.header=X-API-VERSION


#Accept:application/json;version=2
spring.mvc.apiversion.use.media-type-parameter[application/json]=version
